version: '3.7'

services:

  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    ports:
      - 3000:3000
    stdin_open: true
